name: code_base
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  easy_localization: ^3.0.5
  go_router: ^13.2.0
  flutter_screenutil: ^5.9.0
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.7
  lottie: ^3.1.0
  modal_bottom_sheet: ^2.1.2
  cached_network_image: ^3.3.1
  rxdart: ^0.27.7
  pull_to_refresh_flutter3: ^2.0.2
  shimmer: ^3.0.0
  equatable: ^2.0.5
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  auto_route: ^7.9.0
  timeago: ^3.6.1
  firebase_core: ^2.17.1

  email_validator: ^2.1.17
  diacritic: ^0.1.5
  flutter_widget_from_html: ^0.14.11
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.1


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/
    - assets/lotties/


  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    - family: Myriad Pro
      fonts:
        - asset: assets/fonts/Myriad_Pro_Italic.OTF
          style: italic
        - asset: assets/fonts/Myriad_Pro_Regular.OTF
        - asset: assets/fonts/Myriad_Pro_Light.OTF
          weight: 300
        - asset: assets/fonts/Myriad_Pro_Light.OTF
          weight: 300
          style: italic
        - asset: assets/fonts/Myriad_Pro_Semibold.OTF
          weight: 600
        - asset: assets/fonts/Myriad_Pro_Semibold_Italic.OTF
          weight: 600
          style: italic
        - asset: assets/fonts/Myriad_Pro_Bold.OTF
          weight: 700
        - asset: assets/fonts/Myriad_Pro_Bold_Italic.OTF
          weight: 700
          style: italic
        - asset: assets/fonts/Myriad_Pro_Black_Cond.OTF
          weight: 900
        - asset: assets/fonts/Myriad_Pro_Black_Cond_Italic.OTF
          weight: 900
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
